/** Deduped grid cells for the schematic Nepal map (from original HTML). */
const raw = [
  { r: 0, c: 0, id: "humla" },
  { r: 0, c: 1, id: "mugu" },
  { r: 0, c: 2, id: "dolpa" },
  { r: 0, c: 3, id: "mustang" },
  { r: 0, c: 4, id: "manang" },
  { r: 0, c: 5, id: "rasuwa" },
  { r: 0, c: 6, id: "sindhupalchok" },
  { r: 0, c: 7, id: "solukhumbu" },
  { r: 0, c: 8, id: "sankhuwasabha" },
  { r: 0, c: 9, id: "taplejung" },
  { r: 1, c: 0, id: "bajhang" },
  { r: 1, c: 1, id: "jumla" },
  { r: 1, c: 2, id: "kalikot" },
  { r: 1, c: 3, id: "rukum-w" },
  { r: 1, c: 4, id: "rolpa" },
  { r: 1, c: 5, id: "baglung" },
  { r: 1, c: 6, id: "myagdi" },
  { r: 1, c: 7, id: "gorkha" },
  { r: 1, c: 8, id: "nuwakot" },
  { r: 1, c: 9, id: "dolakha" },
  { r: 1, c: 10, id: "okhaldhunga" },
  { r: 1, c: 11, id: "bhojpur" },
  { r: 1, c: 12, id: "dhankuta" },
  { r: 1, c: 13, id: "panchthar" },
  { r: 2, c: 0, id: "darchula" },
  { r: 2, c: 1, id: "bajura" },
  { r: 2, c: 2, id: "dailekh" },
  { r: 2, c: 3, id: "jajarkot" },
  { r: 2, c: 4, id: "rukum-e" },
  { r: 2, c: 5, id: "pyuthan" },
  { r: 2, c: 6, id: "parbat" },
  { r: 2, c: 7, id: "kaski" },
  { r: 2, c: 8, id: "lamjung" },
  { r: 2, c: 9, id: "dhading" },
  { r: 2, c: 10, id: "kavrepalanchok" },
  { r: 2, c: 11, id: "ramechhap" },
  { r: 2, c: 12, id: "khotang" },
  { r: 2, c: 13, id: "ilam" },
  { r: 3, c: 0, id: "achham" },
  { r: 3, c: 1, id: "doti" },
  { r: 3, c: 2, id: "surkhet" },
  { r: 3, c: 3, id: "salyan" },
  { r: 3, c: 4, id: "gulmi" },
  { r: 3, c: 5, id: "arghakhanchi" },
  { r: 3, c: 6, id: "syangja" },
  { r: 3, c: 7, id: "tanahu" },
  { r: 3, c: 8, id: "makwanpur" },
  { r: 3, c: 9, id: "kathmandu" },
  { r: 3, c: 10, id: "bhaktapur" },
  { r: 3, c: 11, id: "lalitpur" },
  { r: 3, c: 12, id: "sindhuli" },
  { r: 3, c: 13, id: "terhathum" },
  { r: 4, c: 0, id: "baitadi" },
  { r: 4, c: 1, id: "dadeldhura" },
  { r: 4, c: 2, id: "dang" },
  { r: 4, c: 3, id: "palpa" },
  { r: 4, c: 4, id: "nawalparasi-w" },
  { r: 4, c: 5, id: "nawalparasi-e" },
  { r: 4, c: 6, id: "chitwan" },
  { r: 4, c: 7, id: "makwanpur" },
  { r: 4, c: 8, id: "parsa" },
  { r: 4, c: 9, id: "bara" },
  { r: 4, c: 10, id: "rautahat" },
  { r: 4, c: 11, id: "udayapur" },
  { r: 4, c: 12, id: "morang" },
  { r: 4, c: 13, id: "jhapa" },
  { r: 5, c: 0, id: "kailali" },
  { r: 5, c: 1, id: "banke" },
  { r: 5, c: 2, id: "bardiya" },
  { r: 5, c: 3, id: "kapilvastu" },
  { r: 5, c: 4, id: "rupandehi" },
  { r: 5, c: 5, id: "nawalparasi-w" },
  { r: 5, c: 7, id: "chitwan" },
  { r: 5, c: 8, id: "sarlahi" },
  { r: 5, c: 9, id: "mahottari" },
  { r: 5, c: 10, id: "dhanusa" },
  { r: 5, c: 11, id: "siraha" },
  { r: 5, c: 12, id: "saptari" },
  { r: 5, c: 13, id: "sunsari" },
  { r: 6, c: 0, id: "kanchanpur" },
];

const seen = new Set();
export const NEPAL_MAP_CELLS = raw.filter((g) => {
  if (seen.has(g.id)) return false;
  seen.add(g.id);
  return true;
});
