import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const htmlPath = path.join(root, "nepal-v8-readable.html");
const html = fs.readFileSync(htmlPath, "utf8");

function slugify(str) {
  return String(str)
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extractArray(constName, endMarker) {
  const prefix = `const ${constName} = `;
  const i = html.indexOf(prefix);
  if (i < 0) throw new Error(`Missing ${constName}`);
  const start = i + prefix.length;
  const j = html.indexOf(endMarker, start);
  if (j < 0) throw new Error(`Missing end marker for ${constName}`);
   const raw = html.slice(start, j).trim();
  if (!raw.startsWith("[") || !raw.endsWith("];")) {
    throw new Error(`Unexpected ${constName} shape`);
  }
  const expr = raw.slice(0, -1); // `[...]` without trailing `;`
  return new Function(`return ${expr}`)();
}

const DISTRICTS = extractArray(
  "DISTRICTS",
  "// ============================================================\n// BUILD MAP SVG"
).map((d) => ({
  ...d,
  slug: slugify(d.id || d.name),
}));

const PRODUCTS = extractArray(
  "PRODUCTS",
  "// ============================================================\n// MARKET DATA"
).map((p) => {
  const { nepalPrice: _removed, ...rest } = p;
  return {
    ...rest,
    slug: slugify(p.name),
  };
});

const out = `/* Auto-generated by scripts/extract-db.mjs — do not edit by hand */
export const DISTRICTS = ${JSON.stringify(DISTRICTS, null, 2)};

export const PRODUCTS = ${JSON.stringify(PRODUCTS, null, 2)};
`;

const outPath = path.join(root, "data", "db.js");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log("Wrote", outPath, {
  districts: DISTRICTS.length,
  products: PRODUCTS.length,
});
